
ALTER TABLE public.lead_processes
  ADD COLUMN IF NOT EXISTS polo_ativo TEXT,
  ADD COLUMN IF NOT EXISTS polo_passivo TEXT,
  ADD COLUMN IF NOT EXISTS ano_inicio INTEGER,
  ADD COLUMN IF NOT EXISTS tribunal TEXT,
  ADD COLUMN IF NOT EXISTS grau TEXT,
  ADD COLUMN IF NOT EXISTS classe TEXT,
  ADD COLUMN IF NOT EXISTS area TEXT,
  ADD COLUMN IF NOT EXISTS assuntos TEXT[],
  ADD COLUMN IF NOT EXISTS valor_causa NUMERIC,
  ADD COLUMN IF NOT EXISTS envolvidos JSONB DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS movimentacoes JSONB DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS fonte_nome TEXT,
  ADD COLUMN IF NOT EXISTS fonte_tipo TEXT,
  ADD COLUMN IF NOT EXISTS fonte_data_inicio DATE,
  ADD COLUMN IF NOT EXISTS fonte_data_fim DATE,
  ADD COLUMN IF NOT EXISTS escavador_raw JSONB;
